### ISSUE TITLE
Potential race condition when rapidly requesting not-yet-generated classes

### ISSUE THREAD

**Issue by LordMonoxide** [BapCat/Tailor#2]
This needs to be investigated further, as it hasn't been proven to be the issue, but during use of Remodel, it seems that if a class is being requested concurrently, it may generate a bad (possibly empty?) class file that will go undetected, due to there being no actual errors.  Once the autoloader tries to load the class, it includes the bad file without issue, but it doesn't actually contain the class as it should.

Again, this is speculation, and has a high priority to be investigated further.

**Comment by rascopeeko** [comment]
We believe that this is a bizarre race condition on PHP's file_put_contents(), as it does no locking whatsoever.  You would think that one would "win" and write the full file, but we end up with a zero-byte file.

Suggested fix is to always write to a tmpfile first (with a random name) and then move the file into its final location.
